name: ci

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@master
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install Pkgs
        run: yarn
      - name: Format
        run: yarn format
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
